version: '2'
services:
  web:
    image: tutum/apache-php
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./app:/app
    networks:
      - test-network
  db:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
